name: final deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_DIR: terraform

jobs:
  infra-setup:
    runs-on: ubuntu-latest
    outputs:
      app_ip: ${{ steps.app.outputs.app_ip }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.6"

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Backend
        run: |
          chmod +x ./create-backend.sh
          ./create-backend.sh

      # Step 4: Terraform init
      - name: Terraform init
        working-directory: ./terraform/
        run: terraform init

      # Step 5: Terraform apply
      - name: Terraform apply
        working-directory: ./terraform/
        run: terraform apply -auto-approve -lock=false

      # Step 6: Save Terraform output
      - name: Save Terraform output
        working-directory: ./terraform/
        run: terraform output -json > tfoutput.json

      - name: Upload Terraform output
        uses: actions/upload-artifact@v4
        with:
          name: tfoutput
          path: terraform/tfoutput.json

      - name: Save APP Public IP
        id: app
        working-directory: ${{ env.TF_DIR }}
        run: |
          APP_IP=$(terraform output -raw app_public_ip)
          echo "APP_PUBLIC_IP=$APP_IP" >> $GITHUB_ENV
          echo "app_ip=$APP_IP" >> $GITHUB_OUTPUT
